"""PVC-070, PVC-071, PVC-075, PVC-076: skills lint, worked examples meet output contracts, plugin packaging."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import anyio
import pytest

from pe_value_os import __version__
from pe_value_os.skills_lint import lint

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"


def test_skills_lint_passes():
    assert lint(SKILLS) == []


def test_lint_catches_problems(tmp_path):
    d = tmp_path / "bad-skill"
    (d / "references").mkdir(parents=True)
    (d / "SKILL.md").write_text("---\nname: other-name\ndescription: x\n---\nCall `made_up_tool(x)` on "
                                "`imaginary_arr`. See `references/missing.md`.\n", encoding="utf-8")
    problems = lint(tmp_path, tools={"healthcheck"})
    joined = " ".join(problems)
    assert "does not match directory" in joined and "made_up_tool" in joined
    assert "imaginary_arr" in joined and "references/missing.md" in joined


def test_diagnostic_worked_example_meets_output_contract():
    skill = (SKILLS / "pe-value-creation-diagnostic" / "SKILL.md").read_text(encoding="utf-8")
    contract = skill.split("# Output contract", 1)[1].split("\n# ", 1)[0]
    ex = (SKILLS / "pe-value-creation-diagnostic" / "references" / "worked-example.md").read_text(encoding="utf-8")
    headings = ("Summary", "Findings", "Opportunities", "Assumptions", "Risks and counterarguments", "Data gaps",
                "Recommended next actions", "Open questions for management")
    for n, heading in enumerate(headings, start=1):
        assert re.search(rf"^{n}\. \*\*{heading}", contract, re.M), heading
        assert f"## {n}. {heading}" in ex, heading
    assert "requires approval" in ex and "fictional" in ex


@pytest.mark.parametrize("skill", sorted(p.name for p in SKILLS.iterdir() if p.is_dir()))
def test_every_skill_has_generated_worked_example(skill):
    ex = SKILLS / skill / "references" / "worked-example.md"
    text = ex.read_text(encoding="utf-8")
    assert "Generated by `scripts/generate_skill_examples.py`" in text and "## Tool calls in this session" in text


def test_plugin_manifest_matches_package():
    manifest = json.loads((ROOT / ".claude-plugin" / "plugin.json").read_text())
    assert manifest["name"] == "pe-value-creation-os" and manifest["version"] == __version__
    mcp = json.loads((ROOT / ".mcp.json").read_text())
    assert mcp["mcpServers"]["pe-value-creation-os"]["args"][-1] == "mcp-stdio"


def test_stdio_server_serves_tools():
    from mcp.client.session import ClientSession
    from mcp.client.stdio import StdioServerParameters, stdio_client

    params = StdioServerParameters(command=sys.executable, args=["-m", "pe_value_os.cli", "mcp-stdio"],
                                   env={"PVC_ENV": "dev", "PYTHONPATH": str(ROOT / "src"),
                                        "PVC_LOG_LEVEL": "WARNING", "SYSTEMROOT": "C:\\Windows"})

    async def go():
        async with stdio_client(params) as (r, w), ClientSession(r, w) as s:
            await s.initialize()
            return {t.name for t in (await s.list_tools()).tools}

    names = anyio.run(go)
    assert {"propose_opportunity", "size_value_case", "request_approval"} <= names
