"""Generate skills/*/references/worked-example.md from real tool calls (PVC-070, PVC-071).

A scripted MCP client follows each skill's procedure against the fictional fixture companies through the
in-process MCP server, and writes the skill's output contract populated only from tool results. This is a
deterministic stand-in for a live model session: it proves the tools can satisfy each output contract, and
gives the model a concrete example. Re-run after tool or fixture changes:

    PVC_ENV=dev python scripts/generate_skill_examples.py
"""

from __future__ import annotations

import io
import json
import sys
import tempfile
from decimal import Decimal
from pathlib import Path
from typing import Any

import anyio
from mcp import Client

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from pe_value_os import security  # noqa: E402
from pe_value_os.adapters.evidence_store import FileSystemEvidenceStore  # noqa: E402
from pe_value_os.adapters.fixtures import FixtureAdapter  # noqa: E402
from pe_value_os.adapters.repositories import InMemoryRepository  # noqa: E402
from pe_value_os.mcp_server import build_server  # noqa: E402
from pe_value_os.observability import configure_logging  # noqa: E402
from pe_value_os.policy import get_policy  # noqa: E402
from pe_value_os.tools import _runtime  # noqa: E402
from pe_value_os.workflows.steps import RunContext  # noqa: E402

HEADER = (
    "> Generated by `scripts/generate_skill_examples.py` from real tool calls against a **fictional** fixture "
    "company. Every number below is copied from a tool result. Do not edit by hand.\n\n"
)


def pct(x: Any) -> str:
    return "n/a" if x is None else f"{Decimal(str(x)) * 100:.1f}%"


def money(x: Any) -> str:
    return "n/a" if x is None else f"{Decimal(str(x)):,.0f}"


def short(ids: list[str]) -> str:
    return ", ".join(f"`{i[:8]}`" for i in ids[:3]) + (" ..." if len(ids) > 3 else "")


class Session:
    def __init__(self, c: Client):
        self.c = c
        self.calls: list[str] = []

    async def tool(self, name: str, **args: Any) -> Any:
        self.calls.append(f"{name}({', '.join(f'{k}={v!r}' for k, v in args.items())})")
        r = await self.c.call_tool(name, args)
        if r.is_error:
            raise RuntimeError(f"{name} failed: {r.content[0].text}")
        sc = r.structured_content
        return sc["result"] if isinstance(sc, dict) and set(sc) == {"result"} else sc

    def transcript(self) -> str:
        return (
            "## Tool calls in this session\n\n" + "\n".join(f"{i}. `{c}`" for i, c in enumerate(self.calls, 1)) + "\n"
        )


def scen(i: str, r: str) -> dict[str, str]:
    return {"improvement_rate": i, "realization_rate": r}


async def diagnostic(s: Session) -> str:
    cid = "beacon-pricing"
    run = (await s.tool("start_diagnostic_run", company_id=cid, mode="interactive"))["run_id"]
    prof = await s.tool("get_company_profile", company_id=cid)
    suff = {
        a: await s.tool("check_data_sufficiency", company_id=cid, analysis=a)
        for a in ("unit_economics", "pricing", "retention", "ai_opportunity")
    }
    pw = await s.tool("price_waterfall", company_id=cid)
    m = (await s.tool("compute_saas_metrics", company_id=cid))["metrics"]
    ev = pw["evidence_ids"]
    hd = max((d for d in pw["dispersion"] if d["lines"] >= 10), key=lambda d: Decimal(d["discount_sd"]))
    findings = [
        (
            "Wide discount dispersion",
            f"New-deal discount standard deviation in {hd['segment']} is {pct(hd['discount_sd'])} "
            f"across {hd['lines']} deals.",
            "high",
        ),
        (
            "Renewal uplifts largely waived",
            f"Realized renewal uplift {pct(pw['renewal_realization']['mean_realized_uplift'])} "
            f"against {pct(pw['renewal_realization']['mean_contracted_uplift'])} contracted.",
            "high",
        ),
        (
            "ARR on legacy price books",
            f"{pct(pw['legacy']['legacy_arr_share'])} of ARR is on legacy price books.",
            "high",
        ),
    ]
    fids = []
    for title, stmt, conf in findings:
        f = await s.tool(
            "record_finding",
            run_id=run,
            finding_type="observation",
            title=title,
            statement=stmt,
            confidence=conf,
            evidence_ids=ev,
        )
        fids.append((f["finding_id"], stmt, conf))
    props = [
        (
            "Discount governance in " + hd["segment"],
            "discounted_arr",
            {"segment": hd["segment"]},
            scen("0.02", "0.5"),
            scen("0.04", "0.6"),
            scen("0.06", "0.75"),
            "60000",
        ),
        (
            "Enforce contracted renewal uplifts",
            "renewing_arr",
            None,
            scen("0.02", "0.5"),
            scen("0.03", "0.65"),
            scen("0.045", "0.8"),
            "40000",
        ),
        (
            "Migrate legacy price-book customers",
            "legacy_price_book_arr",
            None,
            scen("0.1", "0.4"),
            scen("0.2", "0.55"),
            scen("0.25", "0.7"),
            "75000",
        ),
    ]
    rows = []
    for title, metric, params, lo, ba, hi, one in props:
        o = await s.tool(
            "propose_opportunity",
            run_id=run,
            lever="pricing",
            baseline_metric=metric,
            title=title,
            low=lo,
            base=ba,
            high=hi,
            confidence="medium",
            rationale=title,
            evidence_ids=ev,
            one_time_cost=one,
            **({"metric_params": params} if params else {}),
        )
        vc = await s.tool("size_value_case", company_id=cid, opportunity_id=o["opportunity_id"])
        rows.append((o, vc))
    ranks = {p["opportunity_id"]: p for p in await s.tool("prioritize_opportunities", run_id=run)}
    plan = await s.tool("draft_100_day_plan", run_id=run)
    await s.tool("request_approval", run_id=run)
    gaps = [f"{a}: {g['detail']}" for a, r in suff.items() for g in r["gaps"]]
    out = [f"# Worked example: value-creation diagnostic ({prof['profile']['name']})\n\n", HEADER]
    out.append("## 1. Summary\n\n")
    out.append(
        f"- Total base-case run-rate EBITDA across included initiatives: {money(plan['total_run_rate_ebitda_base'])} "
        "(sum returned by `draft_100_day_plan`).\n"
    )
    out.append(f"- Price leakage is the primary lever: {findings[0][1]}\n")
    out.append(f"- {findings[1][1]}\n- {findings[2][1]}\n")
    out.append(
        f"- CAC payback is {m['cac_payback_months']['value']} months ({m['cac_payback_months']['variant']}); "
        "check pricing before attributing it to go-to-market spend.\n\n"
    )
    out.append("## 2. Findings\n\n| Finding id | Statement | Confidence | Evidence |\n|---|---|---|---|\n")
    out += [f"| `{fid[:8]}` | {st} | {cf} | {short(ev)} |\n" for fid, st, cf in fids]
    out.append(
        "\n## 3. Opportunities\n\n| Id | Lever | Low / base / high annual EBITDA | One-time cost | Confidence | Rank |\n"
        "|---|---|---|---|---|---|\n"
    )
    for o, vc in rows:
        rk = ranks.get(o["opportunity_id"], {}).get("rank", "-")
        out.append(
            f"| `{o['opportunity_id'][:8]}` {o['title']} | {o['lever']} | {money(vc['annual_ebitda_low'])} / "
            f"{money(vc['annual_ebitda_base'])} / {money(vc['annual_ebitda_high'])} | {money(vc['one_time_cost'])} | "
            f"{o['confidence']} | {rk} |\n"
        )
    out.append("\n## 4. Assumptions\n\n")
    for o, _ in rows:
        out.append(
            f"- {o['title']}: base improvement {o['base']['improvement_rate']} × realization "
            f"{o['base']['realization_rate']} (analyst judgment); baseline `{o['baseline_metric']}` = "
            f"{money(o['baseline_value'])} and flow-through {o['ebitda_flow_through']} derived by the server.\n"
        )
    out.append(
        "\n## 5. Risks and counterarguments\n\n- The three pricing opportunities act on overlapping ARR and were "
        "sized independently; the combined effect is likely lower than the sum.\n- Price actions can raise churn; "
        "the realization rates carry that response and should be checked against renewal history.\n\n"
    )
    out.append(
        "## 6. Data gaps\n\n" + ("".join(f"- {g}\n" for g in gaps) or "- None: all four analyses were SUFFICIENT.\n")
    )
    out.append(
        "\n## 7. Recommended next actions (each requires approval)\n\n"
        "- Adopt discount approval thresholds and quarter-end controls (*requires approval*).\n"
        "- Enforce contracted renewal uplifts in the next renewal cycle (*requires approval*).\n"
        "- Plan legacy price-book migration at renewal (*requires approval*).\n\n"
    )
    out.append(
        "## 8. Open questions for management\n\n- Which contracts carry price caps or MFN clauses beyond those in "
        "the contract data?\n- Who approves discounts today, and how are exceptions recorded?\n\n"
    )
    return "".join(out) + s.transcript()


async def pricing(s: Session) -> str:
    cid = "beacon-pricing"
    pw = await s.tool("price_waterfall", company_id=cid)
    t = pw["total"]
    out = [
        "# Worked example: pricing (Beacon, fictional)\n\n",
        HEADER,
        "## Waterfall by segment\n\n"
        "| Segment | List | On-invoice leakage | Off-invoice leakage | Pocket realization |\n|---|---|---|---|---|\n",
    ]
    for seg, lay in pw["by_segment"].items():
        out.append(
            f"| {seg} | {money(lay['list_revenue'])} | {pct(lay['on_invoice_leakage_rate'])} | "
            f"{pct(lay['off_invoice_leakage_rate'])} | {pct(lay['pocket_price_realization'])} |\n"
        )
    out.append(
        f"| **total** | {money(t['list_revenue'])} | {pct(t['on_invoice_leakage_rate'])} | "
        f"{pct(t['off_invoice_leakage_rate'])} | {pct(t['pocket_price_realization'])} |\n\n"
    )
    out.append(f"Evidence: {short(pw['evidence_ids'])}\n\n## Findings\n\n")
    out += [
        f"- {d['segment']}: new-deal discount mean {pct(d['mean_discount_rate'])}, standard deviation "
        f"{pct(d['discount_sd'])} ({d['lines']} deals)\n"
        for d in pw["dispersion"]
    ]
    out.append(f"- Quarter-end discount gap: {pct(pw['quarter_end_discount_gap'])}\n")
    rr = pw["renewal_realization"]
    out.append(
        f"- Renewal realization: {pct(rr['mean_realized_uplift'])} realized vs {pct(rr['mean_contracted_uplift'])} "
        f"contracted over {rr['renewals']} renewals\n- Legacy price books: {pct(pw['legacy']['legacy_arr_share'])} "
        f"of ARR; uplift to current list {money(pw['legacy']['uplift_to_current_list'])}\n\n"
    )
    cc = pw["contract_constraints"]
    out.append(
        f"## Contract constraints (checked)\n\n- Active contracts: {cc['active_contracts']}; capped "
        f"{pct(cc['capped_share'])}; CPI-linked {pct(cc['cpi_linked_share'])}; MFN {pct(cc['mfn_share'])}; "
        f"notice {cc['min_notice_days']}-{cc['max_notice_days']} days\n\n## Customer-response assumption\n\n"
        "Churn and downgrade response to any price action is carried in each opportunity's realization rate.\n\n"
    )
    return "".join(out) + s.transcript()


async def unit_economics(s: Session) -> str:
    cid = "cedar-churn"
    m = (await s.tool("compute_saas_metrics", company_id=cid))["metrics"]
    names = [
        "arr",
        "grr",
        "nrr",
        "subscription_gross_margin",
        "cac_payback_months",
        "ltv_to_cac",
        "magic_number",
        "burn_multiple",
        "rule_of_40",
    ]
    out = [
        "# Worked example: SaaS unit economics (Cedar, fictional)\n\n",
        HEADER,
        "## Metric table\n\n| Metric | Value | Period end | Variant | Evidence | Peer p50 |\n|---|---|---|---|---|---|\n",
    ]
    for n in names:
        mv = m[n]
        peer = "-"
        if n in (
            "grr",
            "nrr",
            "cac_payback_months",
            "magic_number",
            "rule_of_40",
            "burn_multiple",
            "subscription_gross_margin",
        ):
            b = await s.tool("get_benchmarks", metric=n, peer_set="b2b_saas_10_50m_arr")
            peer = f"{b['p50']} (synthetic)"
        out.append(
            f"| {n} | {mv['value']} | {mv['period_end']} | {mv['variant']} | {short(mv['evidence_ids'])} | {peer} |\n"
        )
    out.append(
        "\n## Hand-offs\n\n- GRR below policy: hand off to `customer-retention`.\n"
        "- Weak CAC payback with high churn: net new ARR is depressed by churn, so route to retention before "
        "cutting go-to-market spend.\n\n## Data-quality flags\n\n- None raised by the tool for this company.\n\n"
    )
    return "".join(out) + s.transcript()


async def retention(s: Session) -> str:
    cid = "cedar-churn"
    ra = await s.tool("compute_retention_cohorts", company_id=cid)
    cs = await s.tool("get_churn_summary", company_id=cid)
    out = [
        "# Worked example: customer retention (Cedar, fictional)\n\n",
        HEADER,
        f"## Headline\n\n| GRR | NRR | Logo retention | Failed-payment share of churned ARR | Evidence |\n|---|---|---|---|---|\n"
        f"| {pct(ra['grr'])} | {pct(ra['nrr'])} | {pct(ra['logo_retention'])} | {pct(ra['involuntary_payment_share'])} | "
        f"{short(ra['evidence_ids'])} |\n\n## Segments (observed)\n\n| Segment | Opening ARR | GRR | NRR |\n|---|---|---|---|\n",
    ]
    for sgm in ra["segments"]:
        if sgm["dimension"] == "segment":
            out.append(f"| {sgm['value']} | {money(sgm['opening_arr'])} | {pct(sgm['grr'])} | {pct(sgm['nrr'])} |\n")
    out.append(
        f"\n## Drivers\n\n- Observed: first-renewal customers are {ra['early_life_churn_overrepresentation']}x "
        "over-represented in voluntary churn.\n- Hypothesis (medium confidence): onboarding or fit problem; "
        f"reason codes {json.dumps(cs['voluntary_reason_codes'])} are sales-entered and need corroboration.\n\n"
        "## Leading indicators\n\n"
    )
    out += [
        f"- {li['name']}: churned {li['churned_value']} vs retained {li['retained_value']} "
        f"(lead {li['lead_months']} months; signal={li['signal']})\n"
        for li in ra["leading_indicators"]
    ]
    out.append("\n")
    return "".join(out) + s.transcript()


async def ai(s: Session) -> str:
    cid = "cedar-churn"
    sup = await s.tool("get_support_metrics", company_id=cid)
    out = [
        "# Worked example: AI opportunity assessment (Cedar, fictional)\n\n",
        HEADER,
        f"## Support volume (trailing 12 months)\n\n- Tickets: {sup['tickets']}; by tier "
        f"{json.dumps(sup['tickets_by_tier'])}; by category {json.dumps(sup['tickets_by_category'])}\n"
        f"- Average handle minutes by tier: {json.dumps(sup['avg_handle_minutes_by_tier'])}\n"
        f"- Evidence: {short(sup['evidence_ids'])}\n\n## Candidates\n\n| Workflow | Sizeable | Notes |\n|---|---|---|\n"
        "| Tier-1 support deflection | yes | measured volume and cost; deflection rate is an assumption until piloted |\n"
        "| Finance operations automation | no | data needed: transaction volumes by process |\n"
        "| Billing operations automation | no | data needed: exception and dispute volumes |\n\n"
        "Revenue-side AI features are handed to pricing or retention rather than sized here.\n\n",
    ]
    return "".join(out) + s.transcript()


async def planning(s: Session) -> str:
    cid = "beacon-pricing"
    run = (await s.tool("start_diagnostic_run", company_id=cid, mode="interactive"))["run_id"]
    pw = await s.tool("price_waterfall", company_id=cid)
    o = await s.tool(
        "propose_opportunity",
        run_id=run,
        lever="pricing",
        baseline_metric="legacy_price_book_arr",
        title="Migrate legacy price-book customers",
        low=scen("0.1", "0.4"),
        base=scen("0.2", "0.55"),
        high=scen("0.25", "0.7"),
        confidence="medium",
        rationale="Legacy share above policy",
        evidence_ids=pw["evidence_ids"],
        one_time_cost="75000",
    )
    await s.tool("size_value_case", company_id=cid, opportunity_id=o["opportunity_id"])
    await s.tool("prioritize_opportunities", run_id=run)
    plan = await s.tool("draft_100_day_plan", run_id=run)
    out = [
        "# Worked example: 100-day plan (Beacon, fictional)\n\n",
        HEADER,
        f"## Plan summary\n\nTotal base-case run-rate EBITDA {money(plan['total_run_rate_ebitda_base'])}; in-year "
        f"{money(plan['total_in_year_ebitda_base'])}.\n\n## Workstreams\n\n",
    ]
    for ws in plan["workstreams"]:
        out.append(f"### {ws['name']} (owner: {ws['owner_role']})\n\n")
        out += [
            f"- {i['title']} [{i['classification']}]: run-rate {money(i['run_rate_ebitda_base'])}, in-year "
            f"{money(i['in_year_ebitda_base'])}\n"
            for i in ws["initiatives"]
        ]
        for k, v in ws["milestones"].items():
            out.append(f"- **{k}**: " + "; ".join(v) + "\n")
        out.append("\n| KPI | Baseline | Day-100 target | Run-rate target | Monitorable |\n|---|---|---|---|---|\n")
        out += [
            f"| {k['description']} | {k['baseline']} | {k['day_100_target']} | {k['run_rate_target']} | "
            f"{'yes' if k['monitorable'] else 'no'} |\n"
            for k in ws["kpis"]
        ]
        out.append("\n" + "".join(f"- Dependency: {d}\n" for d in ws["dependencies"]))
        out.append("".join(f"- Risk: {r}\n" for r in ws["risks"]) + "\n")
    out.append(
        "## Decisions requiring approval\n\n" + "".join(f"- {d}\n" for d in plan["decisions_requiring_approval"])
    )
    out.append("\n")
    return "".join(out) + s.transcript()


async def main() -> None:
    configure_logging(stream=io.StringIO())
    tmp = Path(tempfile.mkdtemp())
    ctx = RunContext(
        repo=InMemoryRepository(FileSystemEvidenceStore(tmp / "ev")),
        adapter=FixtureAdapter(),
        policy=get_policy(),
        actor="mcp",
    )
    _runtime.set_ctx(ctx)
    jobs = {
        "pe-value-creation-diagnostic": diagnostic,
        "pricing-value-creation": pricing,
        "saas-unit-economics": unit_economics,
        "customer-retention": retention,
        "ai-opportunity-assessment": ai,
        "100-day-planning": planning,
    }
    with security.principal_scope(
        security.Principal(
            subject="model:example", companies=frozenset({"beacon-pricing", "cedar-churn"}), principal_type="model"
        )
    ):
        async with Client(build_server()) as c:
            for skill, fn in jobs.items():
                text = await fn(Session(c))
                path = ROOT / "skills" / skill / "references" / "worked-example.md"
                path.parent.mkdir(exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
                print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    anyio.run(main)
